name: pmi-exam-portal

services:
  postgres:
    image: postgres
    container_name: pmi-exam-portal-postgres
    environment:
      POSTGRES_DB: pmi-exam-portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "35432:5432"
    volumes:
      - pmi-exam-portal_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pmi-exam-portal_postgres_data:

